data_set = {
    "Cristiano Ronaldo": {"occupation": "Footballer", "location": "Portugal", "followers": 635},
    "Lionel Messi": {"occupation": "Footballer", "location": "Argentina", "followers": 505},
    "Selena Gomez": {"occupation": "Singer and actress", "location": "United States", "followers": 430},
    "Kylie Jenner": {"occupation": "Media personality", "location": "United States", "followers": 400},
    "Dwayne Johnson": {"occupation": "Actor and wrestler", "location": "United States", "followers": 395},
    "Ariana Grande": {"occupation": "Singer", "location": "United States", "followers": 380},
    "Kim Kardashian": {"occupation": "Media personality", "location": "United States", "followers": 365},
    "Beyoncé": {"occupation": "Singer", "location": "United States", "followers": 320},
    "Taylor Swift": {"occupation": "Singer", "location": "United States", "followers": 315},
    "Justin Bieber": {"occupation": "Singer", "location": "Canada", "followers": 295},
    "Kendall Jenner": {"occupation": "Model", "location": "United States", "followers": 290},
    "Khloé Kardashian": {"occupation": "Media personality", "location": "United States", "followers": 285},
    "Nike": {"occupation": "Sportswear brand", "location": "United States", "followers": 305},
    "National Geographic": {"occupation": "Magazine", "location": "United States", "followers": 285},
    "Jennifer Lopez": {"occupation": "Singer and actress", "location": "United States", "followers": 252},
    "Neymar": {"occupation": "Footballer", "location": "Brazil", "followers": 225},
    "Virat Kohli": {"occupation": "Cricketer", "location": "India", "followers": 270},
    "Miley Cyrus": {"occupation": "Singer", "location": "United States", "followers": 212},
    "Katy Perry": {"occupation": "Singer", "location": "United States", "followers": 204},
    "Zendaya": {"occupation": "Actress", "location": "United States", "followers": 185},
    "Cardi B": {"occupation": "Rapper", "location": "United States", "followers": 170},
    "LeBron James": {"occupation": "Basketball player", "location": "United States", "followers": 160},
    "Rihanna": {"occupation": "Singer and entrepreneur", "location": "Barbados", "followers": 155},
    "Drake": {"occupation": "Rapper", "location": "Canada", "followers": 145},
    "Shakira": {"occupation": "Singer", "location": "Colombia", "followers": 92},
    "Billie Eilish": {"occupation": "Singer", "location": "United States", "followers": 125},
    "Chris Hemsworth": {"occupation": "Actor", "location": "Australia", "followers": 58},
    "Tom Holland": {"occupation": "Actor", "location": "United Kingdom", "followers": 68},
    "Emma Watson": {"occupation": "Actress", "location": "United Kingdom", "followers": 73},
    "Gal Gadot": {"occupation": "Actress", "location": "Israel", "followers": 108},
    "Priyanka Chopra Jonas": {"occupation": "Actress and singer", "location": "India", "followers": 92},
    "Shraddha Kapoor": {"occupation": "Actress", "location": "India", "followers": 94},
    "Narendra Modi": {"occupation": "Politician", "location": "India", "followers": 100},
    "Lisa": {"occupation": "Singer", "location": "Thailand", "followers": 105},
    "Jennie": {"occupation": "Singer", "location": "South Korea", "followers": 88},
    "Rosé": {"occupation": "Singer", "location": "New Zealand", "followers": 81},
    "Jisoo": {"occupation": "Singer and actress", "location": "South Korea", "followers": 79},
    "BLACKPINK": {"occupation": "Music group", "location": "South Korea", "followers": 60},
    "BTS": {"occupation": "Music group", "location": "South Korea", "followers": 78},
    "RM": {"occupation": "Singer", "location": "South Korea", "followers": 47},
    "Jungkook": {"occupation": "Singer", "location": "South Korea", "followers": 55},
    "V": {"occupation": "Singer", "location": "South Korea", "followers": 67},
    "Suga": {"occupation": "Singer", "location": "South Korea", "followers": 45},
    "Jackie Chan": {"occupation": "Actor", "location": "Hong Kong", "followers": 38},
    "Donnie Yen": {"occupation": "Actor", "location": "Hong Kong", "followers": 9},
    "Jet Li": {"occupation": "Actor", "location": "China", "followers": 6},
    "Manny Pacquiao": {"occupation": "Boxer", "location": "Philippines", "followers": 8},
    "MrBeast": {"occupation": "YouTuber", "location": "United States", "followers": 115},
    "PewDiePie": {"occupation": "YouTuber", "location": "Sweden", "followers": 21},
    "Markiplier": {"occupation": "YouTuber", "location": "United States", "followers": 15},
    "KSI": {"occupation": "YouTuber and boxer", "location": "United Kingdom", "followers": 13},
    "Logan Paul": {"occupation": "YouTuber and wrestler", "location": "United States", "followers": 27},
    "Jake Paul": {"occupation": "YouTuber and boxer", "location": "United States", "followers": 28},
    "Ryan Reynolds": {"occupation": "Actor", "location": "Canada", "followers": 52},
    "Keanu Reeves": {"occupation": "Actor", "location": "Canada", "followers": 18},
    "Robert Downey Jr": {"occupation": "Actor", "location": "United States", "followers": 58},
    "Chris Evans": {"occupation": "Actor", "location": "United States", "followers": 21},
    "Scarlett Johansson": {"occupation": "Actress", "location": "United States", "followers": 12},
    "Will Smith": {"occupation": "Actor", "location": "United States", "followers": 69},
    "Jason Momoa": {"occupation": "Actor", "location": "United States", "followers": 17},
    "Henry Cavill": {"occupation": "Actor", "location": "United Kingdom", "followers": 27},
    "Johnny Depp": {"occupation": "Actor", "location": "United States", "followers": 29},
    "Leonardo DiCaprio": {"occupation": "Actor", "location": "United States", "followers": 61},
    "Tom Cruise": {"occupation": "Actor", "location": "United States", "followers": 12},
    "Morgan Freeman": {"occupation": "Actor", "location": "United States", "followers": 4},
    "Ed Sheeran": {"occupation": "Singer", "location": "United Kingdom", "followers": 48},
    "Bruno Mars": {"occupation": "Singer", "location": "United States", "followers": 40},
    "Dua Lipa": {"occupation": "Singer", "location": "United Kingdom", "followers": 89},
    "The Weeknd": {"occupation": "Singer", "location": "Canada", "followers": 76},
    "Olivia Rodrigo": {"occupation": "Singer", "location": "United States", "followers": 38},
    "Doja Cat": {"occupation": "Singer and rapper", "location": "United States", "followers": 25},
    "Snoop Dogg": {"occupation": "Rapper", "location": "United States", "followers": 88},
    "Eminem": {"occupation": "Rapper", "location": "United States", "followers": 44},
    "Travis Scott": {"occupation": "Rapper", "location": "United States", "followers": 58},
    "Post Malone": {"occupation": "Singer and rapper", "location": "United States", "followers": 27},
    "Bad Bunny": {"occupation": "Singer", "location": "Puerto Rico", "followers": 46},
    "Anitta": {"occupation": "Singer", "location": "Brazil", "followers": 65},
    "Camila Cabello": {"occupation": "Singer", "location": "Cuba", "followers": 64},
    "Shawn Mendes": {"occupation": "Singer", "location": "Canada", "followers": 71},
    "Zac Efron": {"occupation": "Actor", "location": "United States", "followers": 61},
    "Millie Bobby Brown": {"occupation": "Actress", "location": "United Kingdom", "followers": 63},
    "Sydney Sweeney": {"occupation": "Actress", "location": "United States", "followers": 25},
    "Jenna Ortega": {"occupation": "Actress", "location": "United States", "followers": 38},
    "Andrew Garfield": {"occupation": "Actor", "location": "United Kingdom", "followers": 4},
    "Cillian Murphy": {"occupation": "Actor", "location": "Ireland", "followers": 3},
    "Pedro Pascal": {"occupation": "Actor", "location": "Chile", "followers": 10},
    "Cristiano Ronaldo Jr": {"occupation": "Internet personality", "location": "Portugal", "followers": 2},
    "Khaby Lame": {"occupation": "TikToker", "location": "Italy", "followers": 80},
    "Charli D'Amelio": {"occupation": "TikToker", "location": "United States", "followers": 43},
    "Addison Rae": {"occupation": "TikToker and actress", "location": "United States", "followers": 35},
    "Bella Hadid": {"occupation": "Model", "location": "United States", "followers": 61},
    "Gigi Hadid": {"occupation": "Model", "location": "United States", "followers": 78},
    "Hailey Bieber": {"occupation": "Model", "location": "United States", "followers": 54},
    "David Beckham": {"occupation": "Former footballer", "location": "United Kingdom", "followers": 88},
    "Zlatan Ibrahimović": {"occupation": "Footballer", "location": "Sweden", "followers": 63},
    "Karim Benzema": {"occupation": "Footballer", "location": "France", "followers": 76},
    "Kylian Mbappé": {"occupation": "Footballer", "location": "France", "followers": 122},
    "Erling Haaland": {"occupation": "Footballer", "location": "Norway", "followers": 39},
    "Mohamed Salah": {"occupation": "Footballer", "location": "Egypt", "followers": 64},
    "Kevin Hart": {"occupation": "Comedian and actor", "location": "United States", "followers": 177},
    "Ellen DeGeneres": {"occupation": "TV host", "location": "United States", "followers": 136},
    "Oprah Winfrey": {"occupation": "TV host", "location": "United States", "followers": 22},
    "Gordon Ramsay": {"occupation": "Chef", "location": "United Kingdom", "followers": 18},
    "Jamie Oliver": {"occupation": "Chef", "location": "United Kingdom", "followers": 10},
    "Elon Musk": {"occupation": "Entrepreneur", "location": "United States", "followers": 220},
    "Bill Gates": {"occupation": "Entrepreneur", "location": "United States", "followers": 9},
    "Jeff Bezos": {"occupation": "Entrepreneur", "location": "United States", "followers": 6},
    "NASA": {"occupation": "Space agency", "location": "United States", "followers": 96},
    "FC Barcelona": {"occupation": "Football club", "location": "Spain", "followers": 140},
    "Real Madrid": {"occupation": "Football club", "location": "Spain", "followers": 165}
}



